CREATE SCHEMA IF NOT EXISTS "auth";

CREATE SCHEMA IF NOT EXISTS "travel";

CREATE SCHEMA IF NOT EXISTS "social";

CREATE TYPE trip_visibility AS ENUM (
    'public',
    'friends',
    'private'
);

CREATE TYPE member_role AS ENUM (
    'admin',
    'member'
);

CREATE TYPE friend_request_status AS ENUM (
    'pending',
    'accepted',
    'rejected',
    'canceled'
);

CREATE TABLE IF NOT EXISTS "auth"."users" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" TEXT UNIQUE NOT NULL,
    "username" TEXT UNIQUE NOT NULL,
    "password_hash" TEXT,
    "display_name" TEXT NOT NULL,
    "bio" TEXT,
    "profile_photo_url" TEXT,
    "oauth_provider" TEXT,
    "oauth_id" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "auth"."countries" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "code" CHAR(2) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "auth"."cities" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "country_id" INT NOT NULL,
    UNIQUE ("name", "country_id")
);

CREATE TABLE IF NOT EXISTS "auth"."visited_countries" (
    "user_id" INT NOT NULL,
    "country_id" INT NOT NULL,
    "added_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("user_id", "country_id")
);

ALTER TABLE "auth"."visited_countries" ADD CONSTRAINT "auth_visited_countries_fk_user" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE "auth"."visited_countries" ADD CONSTRAINT "auth_visited_countries_fk_country" FOREIGN KEY ("country_id") REFERENCES "auth"."countries"("id") ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS "social"."friend_requests" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sender_id" INT NOT NULL,
    "receiver_id" INT NOT NULL,
    "status" friend_request_status NOT NULL DEFAULT 'pending',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE "social"."friend_requests" ADD CONSTRAINT "social_friend_requests_sender" FOREIGN KEY ("sender_id") REFERENCES "auth"."users"(id) ON DELETE CASCADE;
ALTER TABLE "social"."friend_requests" ADD CONSTRAINT "social_friend_requests_receiver" FOREIGN KEY ("receiver_id") REFERENCES "auth"."users"(id) ON DELETE CASCADE;
ALTER TABLE "social"."friend_requests" ADD CONSTRAINT "social_friend_Requests_u_sender_receiver" UNIQUE ("sender_id", "receiver_id");
ALTER TABLE "social"."friend_requests" ADD CONSTRAINT "social_friend_Requests_c_self_request" CHECK ("sender_id" <> "receiver_id");
CREATE INDEX "social_friend_requests_i_receiver" ON "social"."friend_requests"("receiver_id") WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS "social"."friendships" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id_1" INT NOT NULL,
    "user_id_2" INT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE "social"."friendships" ADD CONSTRAINT "social_friendships_fk_user1" FOREIGN KEY ("user_id_1") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE "social"."friendships" ADD CONSTRAINT "social_friendships_fk_user2" FOREIGN KEY ("user_id_2") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE "social"."friendships" ADD CONSTRAINT "social_friendships_u_user1_user2" UNIQUE ("user_id_1", "user_id_2");
ALTER TABLE "social"."friendships" ADD CONSTRAINT "social_friendships_c_user1_user2" CHECK ("user_id_1" <> "user_id_2");

CREATE TABLE IF NOT EXISTS "travel"."trips" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "duration" INT NOT NULL,
    "start_date" DATE NOT NULL,
    "end_date" DATE NOT NULL,
    "budget" NUMERIC(10, 2),
    "visibility" trip_visibility NOT NULL DEFAULT 'private',
    "created_by" INT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

ALTER TABLE "travel"."trips" ADD CONSTRAINT "travel_trips_fk_created_by" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE RESTRICT;
ALTER TABLE "travel"."trips" ADD CONSTRAINT "travel_trips_c_dates" CHECK ("end_date" >= "start_date");
ALTER TABLE "travel"."trips" ADD CONSTRAINT "travel_trips_c_budget" CHECK ("budget" IS NULL OR "budget" >= 0);

CREATE TABLE IF NOT EXISTS "travel"."trips_countries" (
    "trip_id" INT NOT NULL,
    "country_id" INT NOT NULL,
    PRIMARY KEY ("trip_id", "country_id")
);

ALTER TABLE "travel"."trips_countries" ADD CONSTRAINT "travel_trip_countries_fk_trip" FOREIGN KEY ("trip_id") REFERENCES "travel"."trips"("id") ON DELETE CASCADE;
ALTER TABLE "travel"."trips_countries" ADD CONSTRAINT "travel_trip_countries_fk_country" FOREIGN KEY ("country_id") REFERENCES "auth"."countries"("id") ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS "travel"."permissions" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" TEXT NOT NULL,
    "description" TEXT
);

ALTER TABLE "travel"."permissions" ADD CONSTRAINT "travel_permissions_u_code" UNIQUE ("code");

CREATE TABLE IF NOT EXISTS "travel"."trip_role_permissions" (
    "trip_id" INT NOT NULL,
    "role" member_role NOT NULL,
    "permission_id" INT NOT NULL,
    "granted_by" INT NOT NULL,
    "granted_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("trip_id", "role", "permission_id")
);

ALTER TABLE "travel"."trip_role_permissions" ADD CONSTRAINT "travel_trip_role_permissions_fk_trip" FOREIGN KEY ("trip_id") REFERENCES "travel"."trips"("id") ON DELETE CASCADE;
ALTER TABLE "travel"."trip_role_permissions" ADD CONSTRAINT "travel_trip_role_permissions_fk_permission" FOREIGN KEY ("permission_id") REFERENCES "travel"."permissions"("id") ON DELETE CASCADE;
ALTER TABLE "travel"."trip_role_permissions" ADD CONSTRAINT "travel_trip_role_permissions_fk_granted_by" FOREIGN KEY ("granted_by") REFERENCES "auth"."users"("id") ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS "travel"."trip_members" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "trip_id" INT NOT NULL,
    "user_id" INT NOT NULL,
    "role" member_role NOT NULL DEFAULT 'member',
    "joined_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE "travel"."trip_members" ADD CONSTRAINT "travel_trip_members_fk_trip" FOREIGN KEY ("trip_id") REFERENCES "travel"."trips"("id") ON DELETE CASCADE;
ALTER TABLE "travel"."trip_members" ADD CONSTRAINT "travel_trip_members_fk_user" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE RESTRICT;
ALTER TABLE "travel"."trip_members" ADD CONSTRAINT "travel_trip_members_u_trip_user" UNIQUE ("trip_id", "user_id");

CREATE TABLE IF NOT EXISTS "travel"."itineraries" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "trip_id" INT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "location" TEXT,
    "expected_price" NUMERIC(10, 2) NOT NULL DEFAULT 0,
    "start_datetime" TIMESTAMPTZ NOT NULL,
    "end_datetime" TIMESTAMPTZ NOT NULL,
    "created_by" INT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE "travel"."itineraries" ADD CONSTRAINT "travel_itineraries_fk_trip" FOREIGN KEY ("trip_id") REFERENCES "travel"."trips"("id") ON DELETE CASCADE;
ALTER TABLE "travel"."itineraries" ADD CONSTRAINT "travel_itineraries_fk_created_by" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE RESTRICT;
ALTER TABLE "travel"."itineraries" ADD CONSTRAINT "travel_itineraries_c_dates" CHECK ("end_datetime" >= "start_datetime");

CREATE TABLE IF NOT EXISTS "travel"."expenses" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "trip_id" INT NOT NULL,
    "title" TEXT NOT NULL,
    "amount" NUMERIC(10, 2),
    "currency" TEXT NOT NULL DEFAULT 'EUR',
    "paid_by" INT NOT NULL,
    "is_paid" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE "travel"."expenses" ADD CONSTRAINT "travel_expenses_fk_trip" FOREIGN KEY ("trip_id") REFERENCES "travel"."trips"("id") ON DELETE CASCADE;
ALTER TABLE "travel"."expenses" ADD CONSTRAINT "travel_expenses_fk_paid_by" FOREIGN KEY ("paid_by") REFERENCES "auth"."users"("id") ON DELETE RESTRICT;
ALTER TABLE "travel"."expenses" ADD CONSTRAINT "travel_expenses_c_amount" CHECK ("amount" > 0);

CREATE TABLE IF NOT EXISTS "travel"."expense_participants" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "expense_id" INT NOT NULL,
    "user_id" INT NOT NULL,
    "amount_owed" NUMERIC (10, 2) NOT NULL,
    "is_paid" BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE "travel"."expense_participants" ADD CONSTRAINT "travel_expense_participants_fk_expense" FOREIGN KEY ("expense_id") REFERENCES "travel"."expenses"("id") ON DELETE CASCADE;
ALTER TABLE "travel"."expense_participants" ADD CONSTRAINT "travel_expense_participants_fk_user" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE RESTRICT;
ALTER TABLE "travel"."expense_participants" ADD CONSTRAINT "travel_expense_participants_c_amount" CHECK ("amount_owed" > 0);

CREATE TABLE IF NOT EXISTS "auth"."refresh_tokens" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INT NOT NULL,
    "token" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "revoked_at" TIMESTAMPTZ
);

ALTER TABLE "auth"."refresh_tokens" ADD CONSTRAINT "auth_refresh_tokens_fk_user" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
CREATE UNIQUE INDEX "auth_refresh_tokens_u_token" ON "auth"."refresh_tokens" ("token");
CREATE INDEX "auth_refresh_tokens_i_user" ON "auth"."refresh_tokens" ("user_id");
