CREATE SCHEMA IF NOT EXISTS "auth";

CREATE SCHEMA IF NOT EXISTS "travel";

CREATE SCHEMA IF NOT EXISTS "social";

CREATE TYPE trip_visibility AS ENUM (
    'public',
    'friends',
    'private'
);

CREATE TYPE member_role AS ENUM (
    'admin',
    'member'
);

CREATE TYPE friend_request_status AS ENUM (
    'pending',
    'accepted',
    'rejected',
    'canceled'
);

CREATE TABLE IF NOT EXISTS "auth"."users" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" TEXT UNIQUE NOT NULL,
    "username" TEXT UNIQUE NOT NULL,
    "password_hash" TEXT,
    "display_name" TEXT NOT NULL,
    "bio" TEXT,
    "profile_photo_url" TEXT,
    "oauth_provider" TEXT,
    "oauth_id" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "auth"."countries" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "code" CHAR(2) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "auth"."cities" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "country_id" INT NOT NULL,
    UNIQUE ("name", "country_id")
);

CREATE TABLE IF NOT EXISTS "auth"."visited_countries" (
    "user_id" INT NOT NULL,
    "country_id" INT NOT NULL,
    "added_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("user_id", "country_id")
);

ALTER TABLE "auth"."cities" ADD CONSTRAINT "auth_cities_fk_country" FOREIGN KEY ("country_id") REFERENCES "auth"."countries"("id") ON DELETE CASCADE;
ALTER TABLE "auth"."visited_countries" ADD CONSTRAINT "auth_visited_countries_fk_user" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE "auth"."visited_countries" ADD CONSTRAINT "auth_visited_countries_fk_country" FOREIGN KEY ("country_id") REFERENCES "auth"."countries"("id") ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS auth_cities_i_country_id ON auth.cities(country_id);

CREATE TABLE IF NOT EXISTS "social"."friend_requests" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sender_id" INT NOT NULL,
    "receiver_id" INT NOT NULL,
    "status" friend_request_status NOT NULL DEFAULT 'pending',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

ALTER TABLE "social"."friend_requests" ADD CONSTRAINT "social_friend_requests_sender" FOREIGN KEY ("sender_id") REFERENCES "auth"."users"(id) ON DELETE CASCADE;
ALTER TABLE "social"."friend_requests" ADD CONSTRAINT "social_friend_requests_receiver" FOREIGN KEY ("receiver_id") REFERENCES "auth"."users"(id) ON DELETE CASCADE;
ALTER TABLE "social"."friend_requests" ADD CONSTRAINT "social_friend_Requests_u_sender_receiver" UNIQUE ("sender_id", "receiver_id");
ALTER TABLE "social"."friend_requests" ADD CONSTRAINT "social_friend_Requests_c_self_request" CHECK ("sender_id" <> "receiver_id");
CREATE INDEX "social_friend_requests_i_receiver" ON "social"."friend_requests"("receiver_id") WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS "social"."friendships" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id_1" INT NOT NULL,
    "user_id_2" INT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE "social"."friendships" ADD CONSTRAINT "social_friendships_fk_user1" FOREIGN KEY ("user_id_1") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE "social"."friendships" ADD CONSTRAINT "social_friendships_fk_user2" FOREIGN KEY ("user_id_2") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE "social"."friendships" ADD CONSTRAINT "social_friendships_u_user1_user2" UNIQUE ("user_id_1", "user_id_2");
ALTER TABLE "social"."friendships" ADD CONSTRAINT "social_friendships_c_user1_user2" CHECK ("user_id_1" <> "user_id_2");

CREATE TABLE IF NOT EXISTS "travel"."trips" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "duration" INT NOT NULL,
    "start_date" DATE NOT NULL,
    "end_date" DATE NOT NULL,
    "budget" NUMERIC(10, 2) NOT NULL DEFAULT 0,
    "visibility" trip_visibility NOT NULL DEFAULT 'private',
    "created_by" INT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

ALTER TABLE "travel"."trips" ADD CONSTRAINT "travel_trips_fk_created_by" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE RESTRICT;
ALTER TABLE "travel"."trips" ADD CONSTRAINT "travel_trips_c_dates" CHECK ("end_date" >= "start_date");
ALTER TABLE "travel"."trips" ADD CONSTRAINT "travel_trips_c_budget" CHECK ("budget" IS NULL OR "budget" >= 0);

CREATE TABLE IF NOT EXISTS "travel"."trips_countries" (
    "trip_id" INT NOT NULL,
    "country_id" INT NOT NULL,
    PRIMARY KEY ("trip_id", "country_id")
);

CREATE TABLE IF NOT EXISTS "travel"."trips_cities" (
    "trip_id" INT NOT NULL,
    "city_id" INT NOT NULL,
    PRIMARY KEY ("trip_id", "city_id")
);

CREATE OR REPLACE FUNCTION travel.enforce_country_matches_existing_cities()
RETURNS TRIGGER AS $$
BEGIN
    -- Ensure a country added to a trip does not conflict with existing cities.
    -- example: if a trip already has city Lisbon (country = PT) then trying to
    -- add country FR will raise. Allowed when the trip has no cities, or when
    -- all existing cities belong to the same country as the NEW.country_id.
    -- example: if a trip has city Lisbon (PT) and city Paris (FR), then adding country PT or FR is allowed, but adding country DE is not allowed.
    IF EXISTS (
        SELECT 1
        FROM travel.trips_cities tc
        JOIN auth.cities c ON c.id = tc.city_id
        WHERE tc.trip_id = NEW.trip_id
          AND c.country_id <> NEW.country_id
    ) THEN
        RAISE EXCEPTION 'Cannot add country to trip because it has cities from a different country';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER travel_trip_country_city_check
BEFORE INSERT OR UPDATE OF trip_id, country_id ON travel.trips_countries
FOR EACH ROW
EXECUTE FUNCTION travel.enforce_country_matches_existing_cities();

CREATE OR REPLACE FUNCTION travel.enforce_city_matches_existing_countries()
RETURNS TRIGGER AS $$
BEGIN
    -- Ensure the trip already lists the city's country. Disallow adding a city
    -- if the trip has no matching country entry. Also disallow if the trip has
    -- a country entry that conflicts with the city's country (handled by the
    -- complementary country trigger when applicable).
    -- example: if a trip has country A and B, you can add cities from A or B, but not C.
    IF NOT EXISTS (
        SELECT 1
        FROM travel.trips_countries tc
        JOIN auth.cities c ON c.id = NEW.city_id
        WHERE tc.trip_id = NEW.trip_id
          AND tc.country_id = c.country_id
    ) THEN
        RAISE EXCEPTION 'Cannot add city % to trip % because the city''s country is not listed for the trip', NEW.city_id, NEW.trip_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER travel_trip_city_country_check
BEFORE INSERT OR UPDATE OF trip_id, city_id ON travel.trips_cities
FOR EACH ROW
EXECUTE FUNCTION travel.enforce_city_matches_existing_countries();

-- When removing a country from a trip, cascade-delete any trip-city rows
-- that belong to that country for the same trip. Example: removing (10, PT)
-- will delete any rows in travel.trips_cities for trip_id = 10 whose city
-- resolves to country PT. This makes the delete explicit and avoids
-- orphaned city associations while matching the UX of "delete country →
-- remove its cities".
-- Example: deleting (trip_id=10, country_id=PT) will delete any rows
-- in travel.trips_cities for trip_id=10 whose city has country_id=PT.
CREATE OR REPLACE FUNCTION travel.prevent_country_delete_if_cities()
RETURNS TRIGGER AS $$
BEGIN
    -- Remove city associations for the trip that belong to the country being deleted.
    DELETE FROM travel.trips_cities tc
    USING auth.cities c
    WHERE tc.city_id = c.id
      AND tc.trip_id = OLD.trip_id
      AND c.country_id = OLD.country_id;

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER travel_prevent_country_delete
BEFORE DELETE ON travel.trips_countries
FOR EACH ROW
EXECUTE FUNCTION travel.prevent_country_delete_if_cities();

ALTER TABLE "travel"."trips_cities" ADD CONSTRAINT "travel_trip_cities_fk_trip" FOREIGN KEY ("trip_id") REFERENCES "travel"."trips"("id") ON DELETE CASCADE;
ALTER TABLE "travel"."trips_cities" ADD CONSTRAINT "travel_trip_cities_fk_city" FOREIGN KEY ("city_id") REFERENCES "auth"."cities"("id") ON DELETE RESTRICT;

ALTER TABLE "travel"."trips_countries" ADD CONSTRAINT "travel_trip_countries_fk_trip" FOREIGN KEY ("trip_id") REFERENCES "travel"."trips"("id") ON DELETE CASCADE;
ALTER TABLE "travel"."trips_countries" ADD CONSTRAINT "travel_trip_countries_fk_country" FOREIGN KEY ("country_id") REFERENCES "auth"."countries"("id") ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS "travel"."permissions" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" TEXT NOT NULL,
    "description" TEXT
);

ALTER TABLE "travel"."permissions" ADD CONSTRAINT "travel_permissions_u_code" UNIQUE ("code");

CREATE TABLE IF NOT EXISTS "travel"."trip_members" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "trip_id" INT NOT NULL,
    "user_id" INT NOT NULL,
    "role" member_role NOT NULL DEFAULT 'member',
    "joined_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

ALTER TABLE "travel"."trip_members" ADD CONSTRAINT "travel_trip_members_fk_trip" FOREIGN KEY ("trip_id") REFERENCES "travel"."trips"("id") ON DELETE CASCADE;
ALTER TABLE "travel"."trip_members" ADD CONSTRAINT "travel_trip_members_fk_user" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE RESTRICT;
ALTER TABLE "travel"."trip_members" ADD CONSTRAINT "travel_trip_members_u_trip_user" UNIQUE ("trip_id", "user_id");

CREATE TABLE IF NOT EXISTS "travel"."itineraries" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "trip_id" INT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "location" TEXT,
    "expected_price" NUMERIC(10, 2) NOT NULL DEFAULT 0,
    "start_datetime" TIMESTAMPTZ NOT NULL,
    "end_datetime" TIMESTAMPTZ NOT NULL,
    "created_by" INT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

ALTER TABLE "travel"."itineraries" ADD CONSTRAINT "travel_itineraries_fk_trip" FOREIGN KEY ("trip_id") REFERENCES "travel"."trips"("id") ON DELETE CASCADE;
ALTER TABLE "travel"."itineraries" ADD CONSTRAINT "travel_itineraries_fk_created_by" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE RESTRICT;
ALTER TABLE "travel"."itineraries" ADD CONSTRAINT "travel_itineraries_c_dates" CHECK ("end_datetime" >= "start_datetime");

CREATE TABLE IF NOT EXISTS "travel"."expenses" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "trip_id" INT NOT NULL,
    "title" TEXT NOT NULL,
    "amount" NUMERIC(10, 2),
    "currency" TEXT NOT NULL DEFAULT 'EUR',
    "paid_by" INT NOT NULL,
    "is_paid" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

ALTER TABLE "travel"."expenses" ADD CONSTRAINT "travel_expenses_fk_trip" FOREIGN KEY ("trip_id") REFERENCES "travel"."trips"("id") ON DELETE CASCADE;
ALTER TABLE "travel"."expenses" ADD CONSTRAINT "travel_expenses_fk_paid_by" FOREIGN KEY ("paid_by") REFERENCES "auth"."users"("id") ON DELETE RESTRICT;
ALTER TABLE "travel"."expenses" ADD CONSTRAINT "travel_expenses_c_amount" CHECK ("amount" > 0);

CREATE TABLE IF NOT EXISTS "travel"."expense_participants" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "expense_id" INT NOT NULL,
    "user_id" INT NOT NULL,
    "amount_owed" NUMERIC (10, 2) NOT NULL,
    "is_paid" BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE "travel"."expense_participants" ADD CONSTRAINT "travel_expense_participants_fk_expense" FOREIGN KEY ("expense_id") REFERENCES "travel"."expenses"("id") ON DELETE CASCADE;
ALTER TABLE "travel"."expense_participants" ADD CONSTRAINT "travel_expense_participants_fk_user" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE RESTRICT;
ALTER TABLE "travel"."expense_participants" ADD CONSTRAINT "travel_expense_participants_c_amount" CHECK ("amount_owed" > 0);

CREATE TABLE IF NOT EXISTS "auth"."refresh_tokens" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INT NOT NULL,
    "token" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "revoked_at" TIMESTAMPTZ
);

ALTER TABLE "auth"."refresh_tokens" ADD CONSTRAINT "auth_refresh_tokens_fk_user" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
CREATE UNIQUE INDEX "auth_refresh_tokens_u_token" ON "auth"."refresh_tokens" ("token");
CREATE INDEX "auth_refresh_tokens_i_user" ON "auth"."refresh_tokens" ("user_id");
