-- Seed Portugal (idempotent). All country codes are distinct.
INSERT INTO auth.countries (name, code)
VALUES ('Portugal', 'PT')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO auth.cities (name, country_id)
VALUES
  ('Abrantes',  (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Sintra',     (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Agueda',      (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Albergaria-a-Velha', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Albufeira', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Alfena',   (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Almada',     (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Almeirim', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Alverca do Ribatejo', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Amadora',    (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Amarante',   (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Seixal',   (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Angra do Heroísmo', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Aveiro',    (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Barcelos',  (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Barreiro',  (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Beja',      (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Braga',   (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Bragança',  (SELECT id FROM auth.countries WHERE code = 'PT')),
  ("Caldas da Rainha", (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Câmara de Lobos', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Caniço',    (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Cartaxo',   (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Castelo Branco', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Chaves',    (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Coimbra',   (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Covilhã', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Elvas', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Entroncamento', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Entroncamento', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Valongo', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Ovar', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Espinho', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Esposende', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Estarreja', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Estremoz', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Évora', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Fafe', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Faro', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Fátima', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Felgueiras', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ("Santa Maria da Feira", (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Figueira da Foz', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Paços de Ferreira', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Funchal', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Lisboa',  (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Porto',   (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Coimbra', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Faro',    (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Funchal', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Lisboa',  (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Porto',   (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Coimbra', (SELECT id FROM auth.countries WHERE code = 'PT')),
  ('Faro',    (SELECT id FROM auth.countries WHERE code = 'PT')),
ON CONFLICT (name, country_id) DO NOTHING;

-- Add more cities by extending the VALUES list above.