FROM maven:3.9-eclipse-temurin-21 AS builder
 
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
 
COPY . .
RUN mvn clean package -DskipTests
 
FROM eclipse-temurin:21-jre
 
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
 
EXPOSE 5024
CMD ["java", "-jar", "app.jar"]