package common.services.user;

import jakarta.persistence.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.List;

/**
 * Represents a user in the database and in Spring Security.
 *
 * This class does two things at once:
 *
 * 1. JPA ENTITY — maps this Java class to the "users" table in the "auth" schema.
 *    Each field annotated with @Column maps to a database column.
 *    Hibernate (the JPA implementation) uses this mapping to read/write rows automatically.
 *
 * 2. SPRING SECURITY UserDetails — by implementing UserDetails, Spring Security
 *    knows how to use this class during authentication. When a user logs in,
 *    Spring calls UserDetailsService.loadUserByUsername() which returns this object,
 *    and then uses the getPassword() and getAuthorities() methods to verify credentials.
 *
 * Database location: schema "auth", table "users"
 */
@Entity // Tells JPA/Hibernate this class is a database entity (maps to a table)
@Table(name = "users", schema = "auth") // Specifies the exact table and schema name
public class User implements UserDetails {

    /**
     * Primary key — maps to the "id" column.
     * IDENTITY strategy means the database auto-generates the ID on INSERT
     * (equivalent to INT GENERATED BY DEFAULT AS IDENTITY in PostgreSQL).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    // Each user must have a unique email — enforced at both DB level (unique = true)
    // and application level. Cannot be null.
    @Column(unique = true, nullable = false)
    private String email;

    // Each user must have a unique username — same constraints as email.
    @Column(unique = true, nullable = false)
    private String username;

    // The Java field is named 'passwordHash' but the DB column is 'password_hash'.
    // @Column(name = ...) bridges that naming difference.
    // We never store plain-text passwords — always BCrypt hashed.
    @Column(name = "password_hash")
    private String passwordHash;

    // Display name is what other users see (e.g. "Pedro Silva").
    // Cannot be null — every user must have one.
    @Column(name = "display_name", nullable = false)
    private String displayName;

    // Optional short bio text shown on the user's profile. Can be null.
    private String bio;

    // URL pointing to the user's profile photo (stored in MinIO/S3, not in the DB directly).
    // Can be null if the user hasn't uploaded a photo.
    @Column(name = "profile_photo_url")
    private String profilePhotoUrl;

    // OAuth fields — only populated when the user signed up via Google/GitHub/etc.
    // Both are null for users who registered with email + password.
    @Column(name = "oauth_provider")
    private String oauthProvider; // e.g. "google", "github"

    @Column(name = "oauth_id")
    private String oauthId; // the unique ID from the OAuth provider

    // Automatically set when the row is first inserted.
    // 'updatable = false' means Hibernate will never change this value after creation.
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    // Updated every time the user's record is modified.
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    // ─── UserDetails interface methods ────────────────────────────────────────
    //
    // Spring Security calls these methods during authentication and authorization.
    // We must implement all of them because we implement UserDetails.

    // Spring uses getUsername() to identify the user — we return email because
    // that's what users log in with (not their display username).
    @Override
    public String getUsername() { return email; }

    // Returns the stored BCrypt hash — Spring Security compares this against
    // the submitted password using BCryptPasswordEncoder.
    @Override
    public String getPassword() { return passwordHash; }

    // Returns the roles/permissions this user has.
    // We return an empty list for now — role management will be added later.
    // An empty list means the user is authenticated but has no special roles.
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() { return List.of(); }

    // The following four methods are account status checks used by Spring Security.
    // We return true for all of them — meaning all accounts are always considered
    // active and valid. If you later add account suspension or password expiry
    // features, these would return false for affected accounts.
    @Override public boolean isAccountNonExpired()     { return true; } // account never expires
    @Override public boolean isAccountNonLocked()      { return true; } // account is never locked
    @Override public boolean isCredentialsNonExpired() { return true; } // password never expires
    @Override public boolean isEnabled()               { return true; } // account is always active
}