-- roles table
CREATE TABLE IF NOT EXISTS roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- permissions table
CREATE TABLE IF NOT EXISTS permissions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- roles_permissions table
CREATE TABLE IF NOT EXISTS roles_permissions (
    role_id INT NOT NULL,
    permission_id INT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE INDEX idx_roles_permissions_permission_id
ON roles_permissions(permission_id);

-- Users table
CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    address TEXT,
    city TEXT,
    postal_code TEXT,
    country TEXT,
    email TEXT NOT NULL UNIQUE,
    hashed_password TEXT NOT NULL,
    role_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
);